spring.rabbitmq.host=instance-2
spring.rabbitmq.port=30030
spring.rabbitmq.username=hansin
spring.rabbitmq.password=123456

dustlight.messenger.oauth2.uri=https://api.dustlight.cn/v1/token/validity
dustlight.messenger.oauth2.client-id=7f62e4cf1030000
dustlight.messenger.oauth2.client-secret=9a8e2325257208e3af8f7999b2e08f86bd97a972