/**
 * 消息推送服务
 * 提供消息推送、消息持久化、消息检索等存储服务。
 *
 * The version of the OpenAPI document: v1
 * Contact: hansin@dustlight.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Configuration } from './configuration';
import { AxiosPromise, AxiosInstance } from 'axios';
import { RequestArgs, BaseAPI } from './base';
/**
 *
 * @export
 * @interface BasicChannel
 */
export interface BasicChannel {
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    description?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof BasicChannel
     */
    owner?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof BasicChannel
     */
    members?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof BasicChannel
     */
    updatedAt?: string;
}
/**
 *
 * @export
 * @interface BasicMessage
 */
export interface BasicMessage {
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    sender?: string;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    receiver?: string;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    channel?: string;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    clientId?: string;
    /**
     *
     * @type {object}
     * @memberof BasicMessage
     */
    content?: object;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof BasicMessage
     */
    readAt?: string;
    /**
     *
     * @type {number}
     * @memberof BasicMessage
     */
    status?: number;
}
/**
 *
 * @export
 * @interface BasicNotification
 */
export interface BasicNotification {
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    templateId?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    channelId?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    sender?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    sentAt?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotification
     */
    status?: string;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof BasicNotification
     */
    content?: {
        [key: string]: object;
    };
}
/**
 *
 * @export
 * @interface BasicNotificationTemplate
 */
export interface BasicNotificationTemplate {
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    owner?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    content?: string;
    /**
     *
     * @type {string}
     * @memberof BasicNotificationTemplate
     */
    status?: string;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof BasicNotificationTemplate
     */
    additional?: {
        [key: string]: object;
    };
}
/**
 *
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    id?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof Channel
     */
    members?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof Channel
     */
    owner?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof Channel
     */
    updatedAt?: string;
}
/**
 *
 * @export
 * @interface Message
 */
export interface Message {
    /**
     *
     * @type {string}
     * @memberof Message
     */
    id?: string;
    /**
     *
     * @type {object}
     * @memberof Message
     */
    content?: object;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    channel?: string;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    sender?: string;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    clientId?: string;
    /**
     *
     * @type {number}
     * @memberof Message
     */
    status?: number;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    receiver?: string;
    /**
     *
     * @type {string}
     * @memberof Message
     */
    readAt?: string;
}
/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof Notification
     */
    content?: {
        [key: string]: object;
    };
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    sender?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    createdAt?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    channelId?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    sentAt?: string;
    /**
     *
     * @type {string}
     * @memberof Notification
     */
    templateId?: string;
}
/**
 *
 * @export
 * @interface NotificationTemplate
 */
export interface NotificationTemplate {
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    content?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    owner?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof NotificationTemplate
     */
    status?: string;
}
/**
 *
 * @export
 * @interface QueryResultChannel
 */
export interface QueryResultChannel {
    /**
     *
     * @type {number}
     * @memberof QueryResultChannel
     */
    count?: number;
    /**
     *
     * @type {Array<Channel>}
     * @memberof QueryResultChannel
     */
    data?: Array<Channel>;
}
/**
 *
 * @export
 * @interface QueryResultNotification
 */
export interface QueryResultNotification {
    /**
     *
     * @type {number}
     * @memberof QueryResultNotification
     */
    count?: number;
    /**
     *
     * @type {Array<Notification>}
     * @memberof QueryResultNotification
     */
    data?: Array<Notification>;
}
/**
 *
 * @export
 * @interface QueryResultNotificationTemplate
 */
export interface QueryResultNotificationTemplate {
    /**
     *
     * @type {number}
     * @memberof QueryResultNotificationTemplate
     */
    count?: number;
    /**
     *
     * @type {Array<NotificationTemplate>}
     * @memberof QueryResultNotificationTemplate
     */
    data?: Array<NotificationTemplate>;
}
/**
 * ChannelsApi - axios parameter creator
 * @export
 */
export declare const ChannelsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建频道
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createChannel: (basicChannel: BasicChannel, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 删除频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteChannel: (id: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 查找频道
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findChannels: (key?: string, page?: number, size?: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 获取频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChannel: (id: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 更新频道
     * @param {string} id
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateChannel: (id: string, basicChannel: BasicChannel, cid?: string, options?: any) => Promise<RequestArgs>;
};
/**
 * ChannelsApi - functional programming interface
 * @export
 */
export declare const ChannelsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建频道
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createChannel(basicChannel: BasicChannel, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Channel>>;
    /**
     *
     * @summary 根据 ID 删除频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteChannel(id: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Channel>>;
    /**
     *
     * @summary 查找频道
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findChannels(key?: string, page?: number, size?: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryResultChannel>>;
    /**
     *
     * @summary 根据 ID 获取频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChannel(id: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Channel>>;
    /**
     *
     * @summary 更新频道
     * @param {string} id
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateChannel(id: string, basicChannel: BasicChannel, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Channel>>;
};
/**
 * ChannelsApi - factory interface
 * @export
 */
export declare const ChannelsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary 创建频道
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createChannel(basicChannel: BasicChannel, cid?: string, options?: any): AxiosPromise<Channel>;
    /**
     *
     * @summary 根据 ID 删除频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteChannel(id: string, cid?: string, options?: any): AxiosPromise<Channel>;
    /**
     *
     * @summary 查找频道
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findChannels(key?: string, page?: number, size?: number, cid?: string, options?: any): AxiosPromise<QueryResultChannel>;
    /**
     *
     * @summary 根据 ID 获取频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChannel(id: string, cid?: string, options?: any): AxiosPromise<Channel>;
    /**
     *
     * @summary 更新频道
     * @param {string} id
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateChannel(id: string, basicChannel: BasicChannel, cid?: string, options?: any): AxiosPromise<Channel>;
};
/**
 * ChannelsApi - object-oriented interface
 * @export
 * @class ChannelsApi
 * @extends {BaseAPI}
 */
export declare class ChannelsApi extends BaseAPI {
    /**
     *
     * @summary 创建频道
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApi
     */
    createChannel(basicChannel: BasicChannel, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Channel>>;
    /**
     *
     * @summary 根据 ID 删除频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApi
     */
    deleteChannel(id: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Channel>>;
    /**
     *
     * @summary 查找频道
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApi
     */
    findChannels(key?: string, page?: number, size?: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<QueryResultChannel>>;
    /**
     *
     * @summary 根据 ID 获取频道
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApi
     */
    getChannel(id: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Channel>>;
    /**
     *
     * @summary 更新频道
     * @param {string} id
     * @param {BasicChannel} basicChannel
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChannelsApi
     */
    updateChannel(id: string, basicChannel: BasicChannel, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Channel>>;
}
/**
 * MessagesApi - axios parameter creator
 * @export
 */
export declare const MessagesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     * 获取与目标的对话
     * @summary 获取消息列表
     * @param {string} target
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChat: (target: string, offset?: string, size?: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     * 以发信者 ID 分组的最新消息列表
     * @summary 获取最新消息列表
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChatList: (offset?: string, size?: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 标记消息为已读
     * @param {Array<string>} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markRead: (requestBody: Array<string>, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     * 如果提供了 channel 则发送给频道内所有人
     * @summary 创建并发送消息
     * @param {BasicMessage} basicMessage
     * @param {string} [channel]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendMessage: (basicMessage: BasicMessage, channel?: string, cid?: string, options?: any) => Promise<RequestArgs>;
};
/**
 * MessagesApi - functional programming interface
 * @export
 */
export declare const MessagesApiFp: (configuration?: Configuration) => {
    /**
     * 获取与目标的对话
     * @summary 获取消息列表
     * @param {string} target
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChat(target: string, offset?: string, size?: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Message>>>;
    /**
     * 以发信者 ID 分组的最新消息列表
     * @summary 获取最新消息列表
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChatList(offset?: string, size?: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Message>>>;
    /**
     *
     * @summary 标记消息为已读
     * @param {Array<string>} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markRead(requestBody: Array<string>, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     * 如果提供了 channel 则发送给频道内所有人
     * @summary 创建并发送消息
     * @param {BasicMessage} basicMessage
     * @param {string} [channel]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendMessage(basicMessage: BasicMessage, channel?: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Message>>>;
};
/**
 * MessagesApi - factory interface
 * @export
 */
export declare const MessagesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     * 获取与目标的对话
     * @summary 获取消息列表
     * @param {string} target
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChat(target: string, offset?: string, size?: number, cid?: string, options?: any): AxiosPromise<Array<Message>>;
    /**
     * 以发信者 ID 分组的最新消息列表
     * @summary 获取最新消息列表
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChatList(offset?: string, size?: number, cid?: string, options?: any): AxiosPromise<Array<Message>>;
    /**
     *
     * @summary 标记消息为已读
     * @param {Array<string>} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markRead(requestBody: Array<string>, cid?: string, options?: any): AxiosPromise<void>;
    /**
     * 如果提供了 channel 则发送给频道内所有人
     * @summary 创建并发送消息
     * @param {BasicMessage} basicMessage
     * @param {string} [channel]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendMessage(basicMessage: BasicMessage, channel?: string, cid?: string, options?: any): AxiosPromise<Array<Message>>;
};
/**
 * MessagesApi - object-oriented interface
 * @export
 * @class MessagesApi
 * @extends {BaseAPI}
 */
export declare class MessagesApi extends BaseAPI {
    /**
     * 获取与目标的对话
     * @summary 获取消息列表
     * @param {string} target
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    getChat(target: string, offset?: string, size?: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Message[]>>;
    /**
     * 以发信者 ID 分组的最新消息列表
     * @summary 获取最新消息列表
     * @param {string} [offset]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    getChatList(offset?: string, size?: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Message[]>>;
    /**
     *
     * @summary 标记消息为已读
     * @param {Array<string>} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    markRead(requestBody: Array<string>, cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     * 如果提供了 channel 则发送给频道内所有人
     * @summary 创建并发送消息
     * @param {BasicMessage} basicMessage
     * @param {string} [channel]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagesApi
     */
    sendMessage(basicMessage: BasicMessage, channel?: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Message[]>>;
}
/**
 * NotificationsApi - axios parameter creator
 * @export
 */
export declare const NotificationsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建并发送通知
     * @param {BasicNotification} basicNotification
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNotification: (basicNotification: BasicNotification, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 删除通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNotification: (id: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 获取通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotification: (id: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 列出通知列表
     * @param {string} [templateId]
     * @param {string} [channelId]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listNotification: (templateId?: string, channelId?: string, page?: number, size?: number, cid?: string, options?: any) => Promise<RequestArgs>;
};
/**
 * NotificationsApi - functional programming interface
 * @export
 */
export declare const NotificationsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建并发送通知
     * @param {BasicNotification} basicNotification
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNotification(basicNotification: BasicNotification, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>>;
    /**
     *
     * @summary 根据 ID 删除通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNotification(id: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary 根据 ID 获取通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotification(id: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>>;
    /**
     *
     * @summary 列出通知列表
     * @param {string} [templateId]
     * @param {string} [channelId]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listNotification(templateId?: string, channelId?: string, page?: number, size?: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryResultNotification>>;
};
/**
 * NotificationsApi - factory interface
 * @export
 */
export declare const NotificationsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary 创建并发送通知
     * @param {BasicNotification} basicNotification
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNotification(basicNotification: BasicNotification, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<Notification>;
    /**
     *
     * @summary 根据 ID 删除通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNotification(id: string, cid?: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary 根据 ID 获取通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotification(id: string, cid?: string, options?: any): AxiosPromise<Notification>;
    /**
     *
     * @summary 列出通知列表
     * @param {string} [templateId]
     * @param {string} [channelId]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listNotification(templateId?: string, channelId?: string, page?: number, size?: number, cid?: string, options?: any): AxiosPromise<QueryResultNotification>;
};
/**
 * NotificationsApi - object-oriented interface
 * @export
 * @class NotificationsApi
 * @extends {BaseAPI}
 */
export declare class NotificationsApi extends BaseAPI {
    /**
     *
     * @summary 创建并发送通知
     * @param {BasicNotification} basicNotification
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    createNotification(basicNotification: BasicNotification, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<Notification>>;
    /**
     *
     * @summary 根据 ID 删除通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    deleteNotification(id: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @summary 根据 ID 获取通知记录
     * @param {string} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    getNotification(id: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<Notification>>;
    /**
     *
     * @summary 列出通知列表
     * @param {string} [templateId]
     * @param {string} [channelId]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApi
     */
    listNotification(templateId?: string, channelId?: string, page?: number, size?: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<QueryResultNotification>>;
}
/**
 * TemplatesApi - axios parameter creator
 * @export
 */
export declare const TemplatesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建模板
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTemplate: (basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 删除模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTemplate: (id: string, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 查找模板
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findTemplates: (key?: string, page?: number, size?: number, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 获取模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTemplate: (id: string, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 根据 ID 更新模板
     * @param {string} id
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTemplate: (id: string, basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any) => Promise<RequestArgs>;
};
/**
 * TemplatesApi - functional programming interface
 * @export
 */
export declare const TemplatesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary 创建模板
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTemplate(basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 删除模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary 查找模板
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findTemplates(key?: string, page?: number, size?: number, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryResultNotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 获取模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 更新模板
     * @param {string} id
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTemplate(id: string, basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * TemplatesApi - factory interface
 * @export
 */
export declare const TemplatesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary 创建模板
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createTemplate(basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<NotificationTemplate>;
    /**
     *
     * @summary 根据 ID 删除模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary 查找模板
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findTemplates(key?: string, page?: number, size?: number, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<QueryResultNotificationTemplate>;
    /**
     *
     * @summary 根据 ID 获取模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<NotificationTemplate>;
    /**
     *
     * @summary 根据 ID 更新模板
     * @param {string} id
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTemplate(id: string, basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): AxiosPromise<void>;
};
/**
 * TemplatesApi - object-oriented interface
 * @export
 * @class TemplatesApi
 * @extends {BaseAPI}
 */
export declare class TemplatesApi extends BaseAPI {
    /**
     *
     * @summary 创建模板
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    createTemplate(basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<NotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 删除模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    deleteTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @summary 查找模板
     * @param {string} [key]
     * @param {number} [page]
     * @param {number} [size]
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    findTemplates(key?: string, page?: number, size?: number, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<QueryResultNotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 获取模板
     * @param {string} id
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    getTemplate(id: string, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<NotificationTemplate>>;
    /**
     *
     * @summary 根据 ID 更新模板
     * @param {string} id
     * @param {BasicNotificationTemplate} basicNotificationTemplate
     * @param {'EMAIL'} [type]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApi
     */
    updateTemplate(id: string, basicNotificationTemplate: BasicNotificationTemplate, type?: 'EMAIL', cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
}
